Repository GoogleCloudPlatform/gke-bazel-demo, pull requests merged in 2019-05, with the labels that each got.

#15 Fixed the shell script errors
  scripts/create.sh
  scripts/teardown.sh
  test/make.sh
Labels: approved, cla: yes, gke-helmsman, size/S

#19 Adding support for kubectl to be compiled
  WORKSPACE
  scripts/create-rbe.sh
  scripts/create.sh
Labels: approved, cla: yes, gke-helmsman, size/M

#39 Implement using Ingress
  .gitignore
  BUILD.bazel
  Makefile
  bazel-0.25.0.bazelrc
  java-spring-boot/BUILD.bazel
  java-spring-boot/manifests/BUILD.bazel
  java-spring-boot/manifests/deployment.yaml
  java-spring-boot/src/main/java/com/example/TodoController.java
  js-client/manifests/deployment.yaml
  js-client/src/images/bazel-navbar.svg
  js-client/src/todos/todos.service.ts
  scripts/create-rbe.sh
  scripts/create.sh
  scripts/destroy_apps.sh
  scripts/validate.sh
Labels: approved, cla: yes, gke-helmsman, size/XL

#18 Unit test running for java
  java-spring-boot/BUILD.bazel
  java-spring-boot/src/main/java/com/example/Demo.java
  java-spring-boot/src/main/java/com/example/TodoController.java
  java-spring-boot/src/test/java/com/example/BUILD.bazel
  java-spring-boot/src/test/java/com/example/DemoTest.java
  java-spring-boot/src/test/java/com/example/TodoControllerTest.java
  scripts/create-rbe.sh
  scripts/validate.sh
Labels: approved, cla: yes, gke-helmsman, size/L

#42 JS client tweaks and Scaling application
  java-spring-boot/manifests/deployment.yaml
  js-client/manifests/deployment.yaml
  js-client/src/BUILD.bazel
  js-client/src/app.component.html
  js-client/src/example/BUILD.bazel
  js-client/src/example/index.html
  js-client/src/hello-world/hello-world.component.html
  js-client/src/todos/todos.component.html
  terraform/main.tf
Labels: approved, cla: yes, gke-helmsman, size/M
